name: Bug Report
description: Let us know if something is broken on PyDM.
labels: [bug]
body:

  - type: markdown
    attributes:
      value: |
        Before reporting, please make a quick search through the existing [open issues](https://github.com/slaclab/pydm/issues?q=is%3Aissue+is%3Aopen),
        and also [closed issues](https://github.com/slaclab/pydm/issues?q=is%3Aissue+is%3Aclosed), to check if it's been previously addressed.

  - type: textarea
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of the bug. May include logs, images, or videos."
      placeholder: "A clear and concise description of the bug. May include logs, images, or videos."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the bug."
      placeholder: "Steps to reproduce the bug."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: dropdown
    id: os-version
    attributes:
      label: "Operating System."
      description: "Select your OS"
      options:
        - Linux
        - Windows
        - macOS
    validations:
      required: true

  - type: input
    id: os-specific-version
    attributes:
      label: "OS Version Details"
      description: "Specify your OS version"
      placeholder: "Specify your OS version (e.g., Ubuntu 22.04, Windows 10, macOS 13.3)."
    validations:
      required: false

  - type: input
    id: pydm-version
    attributes:
      label: "PyDM Version"
      description: "Specify your PyDM version"
      placeholder: "Specify your PyDM version (check with 'pydm --v' or `File > About` in PyDM top-bar menu))."
    validations:
      required: true

  - type: dropdown
    id: qt-wrapper-version
    attributes:
      label: "Qt Python Wrapper"
      description: "Select which Qt Python Wrapper you are running PyDM with (check `File > About` in PyDM, will be either PyQt5 or PySide6)."
      options:
        - PyQt5
        - PySide6
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: "Python Version"
      description: "Specify your Python version"
      placeholder: "Specify your Python version (check this with 'python -V')"
    validations:
      required: true

  - type: textarea
    id: additional-package-versions
    attributes:
      label: "Additional Package Versions"
      description: "Provide versions of other packages PyDM is using that might be relevant to the issue (check `File > About` in PyDM)."
      placeholder: "Example: NumPy v2.2.2 PyQtGraph v.0.12.4"
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Additional context."
      description: "Add any other context, links, etc. about the feature here."
      placeholder: "Add any other context, links, etc. about the feature here."
    validations:
      required: false